apiVersion: v1
kind: ConfigMap
metadata:
  name: commafeed-configmap
data:
  QUARKUS_DATASOURCE_DB_KIND: "postgresql"
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://commafeed-db.6541333.xyz:5432/commafeed"
